strict: true

site_name: tsrc documentation
repo_url: https://github.com/dmerejkowsky/tsrc/

theme:
  name: material
  custom_dir: custom_theme


markdown_extensions:
  - codehilite
  - markdown.extensions.admonition #for !!! notice
  - markdown.extensions.def_list
  - pymdownx.superfences

  - toc:
      permalink: True
      separator: "_"

nav:
- Home: index.md
- Getting Started: getting-started.md

- Guides:
  - Using groups: guide/groups.md
  - Using several remotes: guide/remotes.md
  - Editing workspace configuration: guide/workspace-config.md
  - Running a command for each repo in the workspace: guide/foreach.md

- Reference:
  - Command line usage: ref/cli.md
  - Sync algorithm: ref/sync.md
  - Manifest configuration: ref/manifest-config.md
  - Workspace configuration: ref/workspace-config.md

- Contributing:
    - Using the issue tracker: contrib/issues.md
    - Suggesting changes: contrib/dev.md
    - Code manifesto: code-manifesto.md

- FAQ: faq.md

- Changelog: changelog.md
