site_name: tsrc documentation
repo_url: https://github.com/dmerejkowsky/tsrc/

theme:
  name: readthedocs
  custom_dir: custom_theme

extra_css: [extra.css]
strict: true

markdown_extensions:
  - markdown.extensions.admonition #for !!! notice
  - markdown.extensions.def_list

  - toc:
      permalink: True
      separator: "_"

nav:
- Home: index.md
- Getting Started: getting-started.md

- Guides:
  - Using groups: guide/groups.md
  - Editing workspace configuration: guide/workspace-config.md

- Reference:
  - Command line usage: ref/cli.md
  - Configuration files formats: ref/formats.md
  - Sync algorithm: ref/sync.md

- Contributing: contrib.md

- Code manifesto: code-manifesto.md

- FAQ: faq.md

- Changelog: changelog.md
